# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('contact', models.CharField(blank=True, max_length=22, null=True)),
                ('message', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('not read', 'Not read'), ('read', 'Read'), ('emailed', 'Emailed'), ('called', 'Called'), ('still continuing', 'Still Continuing')], default='not read', max_length=120)),
            ],
        ),
    ]
