# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_message',
            new_name='ContactMessage',
        ),
    ]
